### ISSUE TITLE
Request more styles.

### ISSUE THREAD

**Issue by 3majed** [bkader/Masque-WoTLK#1]
Thanks for backporting masque @bkader.
Would like to see you add these styles if possible
Masque_Caith
Masque_CleanUI
Masque_FlatSquares

**Comment by bkader** [comment]
You're welcome @3majed .. Can you send me links to check please? And I hope they don't have **Mask Textures** because those are the only things unavailable for now until I find a solution.

**Comment by 3majed** [comment]
https://www.curseforge.com/wow/addons/masque-caith
https://www.curseforge.com/wow/addons/buttonfacade-cleanui
https://www.curseforge.com/wow/addons/masque_flatsquares
